global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "nopcommerce"
    metrics_path: /metrics
    static_configs:
      - targets: ["nopcommerce_web:80"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
